baseurl: ""
relativeURLs: "True"
languageCode: "en-us"
title: 'Arcata Food Not Bombs'
theme: "hugo-minimal"
footnotereturnlinkcontents: "↩"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
    - name: Get Involved
      url: "get-involved/"

params:
  description: "Website fof the Arcata Food Not Bombs group."
  footer: "arcatafoodnotbombs.org -- [Github repo](https://github.com/samuelmcpherson/arcatafoodnotbombs.org) -- Contact the site [admin](mailto:contact@samuelmcpherson.net)"