baseurl: ""
relativeURLs: "True"
languageCode: "en-us"
title: 'Arcata Food Not Bombs'
theme: "hugo-minimal"
footnotereturnlinkcontents: "↩"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Get Involved
      url: "get-involved/"

params:
  description: "Website for the promotion of the Arcata Food Not Bombs group."
